name: drury
favicon: null
layout_spectrum: 0.028262676671147346
typography_spectrum: 0.5433979469817132
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4829214138444513
  lightness: 0.3688045695889741
  saturation: 0.02833919203840196
  rhythmicContrast: 0.8787369325291365
purpose: []
